name: 'Possible Page Impact'
description: 'Comment on the possible impact of the PR changes on the page'
author: 'Cut0'

github-token:
  action-input:
    input: GITHUB_TOKEN
    is-default: true
  permissions:
    pull-requests: write
    pull-requests-reason: to create or update PR comment

inputs:
  GITHUB_TOKEN:
    description: "The GitHub access token (e.g. secrets.GITHUB_TOKEN) used to create or update the comment. This defaults to {{ github.token }}."
    default: "${{ github.token }}"
    required: false
  SHA:
    description: "The SHA of the commit to check the impact of."
    default: "${{ github.sha }}"
    required: false
  app_dir:
    description: "The application directory of the project."
    required: true
  pages_pattern:
    description: "The glob pattern to match the pages files."
    required: false
  pages_regex:
    description: "The regex to match the pages files."
    required: false

runs:
  using: "node20"
  main: "dist/index.cjs"
